# Generated by Django 5.0.7 on 2024-11-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_cvdownload_websitevisit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMessage',
            new_name='ContactMessages',
        ),
        migrations.AlterField(
            model_name='websitevisit',
            name='user_ip',
            field=models.CharField(max_length=45),
        ),
    ]
